### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by Chaprnks** [RealAtom/route-tracing#6]
![gaEcyXC](https://user-images.githubusercontent.com/6340970/119204866-a274ed80-ba64-11eb-8063-a3755f49f40c.png)
![XOOGK5m](https://user-images.githubusercontent.com/6340970/119204872-a43eb100-ba64-11eb-9933-083ad316da9f.png)

**Comment by alexchwoj** [comment]
fixed, thx
